---
hugo_env: &hugo_env
  BASE_URL: http://bucket-resto-s3.s3-website-us-east-1.amazonaws.com

kind: pipeline
type: docker
name: hugo-to-s3-deploy

steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *hugo_env
    commands:
      - hugo --baseURL $BASE_URL

  - name: deploy-to-s3
    image: plugins/s3
    settings:
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      secret_token:
        from_secret: AWS_SESSION_TOKEN

      bucket: bucket-resto-s3 
      region: us-east-1   
      
      source: public/**/*
      target: /
      acl: public-read               
      cache_control: max-age=86400
      overwrite: true

    when:
      event: push
      branch:
        - main
        - master